// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO_z8nCtl_TSAFGD8ph_hDMszLa2d6SnY',
    appId: '1:729526504835:web:e4cb9135228d9d25123ab6',
    messagingSenderId: '729526504835',
    projectId: 'whereto-1',
    authDomain: 'whereto-1.firebaseapp.com',
    storageBucket: 'whereto-1.appspot.com',
    measurementId: 'G-B4YWS4EB11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLimBrv02IDhmXPU_m_EvL7FfbufxwRPM',
    appId: '1:729526504835:android:d4e76d3861588540123ab6',
    messagingSenderId: '729526504835',
    projectId: 'whereto-1',
    storageBucket: 'whereto-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsqzGwNXr-RPAHKyDmx-ZxLIe_7YKjMmo',
    appId: '1:729526504835:ios:997deeed74a38ee5123ab6',
    messagingSenderId: '729526504835',
    projectId: 'whereto-1',
    storageBucket: 'whereto-1.appspot.com',
    iosClientId: '729526504835-i32unkpk2hqc9thvnqp1ca0nkenn8ikh.apps.googleusercontent.com',
    iosBundleId: 'com.example.whereTo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsqzGwNXr-RPAHKyDmx-ZxLIe_7YKjMmo',
    appId: '1:729526504835:ios:997deeed74a38ee5123ab6',
    messagingSenderId: '729526504835',
    projectId: 'whereto-1',
    storageBucket: 'whereto-1.appspot.com',
    iosClientId: '729526504835-i32unkpk2hqc9thvnqp1ca0nkenn8ikh.apps.googleusercontent.com',
    iosBundleId: 'com.example.whereTo',
  );
}
